# -*- coding: utf-8 -*-
from dataclasses import dataclass
import os

@dataclass
class Config:
    data_path: str = r"./datasets/GridPulse_Shandong.csv"
    sheet_name: str = "Sheet1"
    time_col: str = "Time"
    target_col: str = "Real-time price"
    output_dir: str = r"./outputs_shandong"
    market: str = "shandong"
    train_ratio: float = 0.7
    val_ratio: float = 0.1
    pred_len: int = 24
    rows: int = 6
    cols: int = 24
    patch_len: int = 6
    warmup_rows: int = 0
    d_model: int = 80
    dropout: float = 0.20
    diffusion_steps: int = 300
    ddim_steps: int = 10
    mc_samples: int = 5
    norm_clip: float = 6.0
    ddim_clip: float = 8.0
    residual_quantile: float = 0.90
    anchor_init_weights: tuple = (0.45, 0.20, 0.25, 0.05, 0.05)
    anchor_correction_init: float = -1.8
    diffusion_gate_bias: float = -4.0
    anchor_weight: float = 1.40
    final_weight: float = 1.10
    robust_weight: float = 0.45
    shape_weight: float = 0.20
    diffusion_weight: float = 0.12
    x0_weight: float = 0.08
    cls_weight: float = 0.08
    gate_reg_weight: float = 0.02
    val_metric_bonus: float = 0.04
    post_calibrate: bool = False
    refit_train_val_epochs: int = 0
    refit_lr: float = 8e-5
    tree_auxiliary: bool = True
    tree_aux_hourly: bool = False
    tree_aux_estimators: int = 160
    tree_aux_max_depth: int = 8
    tree_aux_min_samples_leaf: int = 3
    tree_aux_n_jobs: int = 1
    tree_aux_weight_grid: tuple = (0.50, 0.65, 0.75, 0.85, 1.00)
    tree_aux_min_weight: float = 0.50
    tree_aux_max_weight: float = 1.00
    post_calibrate_ridge: float = 40.0
    post_calibrate_slope_min: float = 0.70
    post_calibrate_slope_max: float = 1.25
    post_calibrate_affine_gain: float = 0.998
    post_calibrate_affine_mix: float = 0.45
    post_calibrate_hours_offset_only: tuple = (10, 11, 12, 13, 14, 15)
    horizon_loss_weights: tuple = (1,1,1,1,1,1,1.1,1.2,1.55,1.85,2.1,2.2,2.2,2.05,1.7,1.4,1.2,1.1,1.05,1.05,1.05,1,1,1)
    batch_size: int = 96
    epochs: int = 300
    patience: int = 60
    lr: float = 3e-4
    weight_decay: float = 3e-4
    ema_decay: float = 0.999
    grad_clip: float = 1.0
    seed: int = 2024
    num_workers: int = 0
    use_gpu: bool = True
    selected_historical_features = ['Real-time tie-line power', 'Real-time load', 'Photovoltaic output', 'wind output', 'Hydro/pumped-storage output', 'local generation', 'Total Self-Owned Generation', 'nuclear output', '2m air temperature', '2m dew-point temperature', 'Sea-level pressure', 'surface pressure', 'Total precipitation', 'rainfall', 'snowfall', '2m relative humidity', 'apparent temperature', '10m gust speed', '10m wind direction', '10m wind speed', '100m wind speed']
    use_future_known_covariates: bool = True
    selected_future_known_features = selected_historical_features
    def ensure_dirs(self): os.makedirs(self.output_dir, exist_ok=True)
